# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

source ~/powerlevel10k/powerlevel10k.zsh-theme

# BEGIN - asdf
# append completions to fpath
. $HOME/.asdf/asdf.sh
fpath=(${ASDF_DIR}/completions $fpath)
# initialise completions with ZSH's compinit
autoload -Uz compinit && compinit
# END - asdf

# BEGIN - Configure history
export HISTFILE=~/.zsh_history
export HISTFILESIZE=100000
export HISTSIZE=10000
export SAVEHIST=100000
setopt EXTENDED_HISTORY
setopt INC_APPEND_HISTORY
export HISTTIMEFORMAT="[%F %T] "
# END - Configure history

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

path=('/home/madis/bin' $path)

if [ -e /home/madis/.nix-profile/etc/profile.d/nix.sh ]; then . /home/madis/.nix-profile/etc/profile.d/nix.sh; fi # added by Nix installer
